//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pec.shaparak.ir
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientPaymentRequestDataBase", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pec.shaparak.ir.ClientSaleRequestData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pec.shaparak.ir.ClientSaleDiscountRequestData))]
    public partial class ClientPaymentRequestDataBase : object
    {
        
        private string LoginAccountField;
        
        private long AmountField;
        
        private long OrderIdField;
        
        private string CallBackUrlField;
        
        private string AdditionalDataField;
        
        private string OriginatorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginAccount
        {
            get
            {
                return this.LoginAccountField;
            }
            set
            {
                this.LoginAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CallBackUrl
        {
            get
            {
                return this.CallBackUrlField;
            }
            set
            {
                this.CallBackUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Originator
        {
            get
            {
                return this.OriginatorField;
            }
            set
            {
                this.OriginatorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientSaleRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pec.shaparak.ir.ClientSaleDiscountRequestData))]
    public partial class ClientSaleRequestData : pec.shaparak.ir.ClientPaymentRequestDataBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientSaleDiscountRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class ClientSaleDiscountRequestData : pec.shaparak.ir.ClientSaleRequestData
    {
        
        private pec.shaparak.ir.Product[] DiscountProductField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public pec.shaparak.ir.Product[] DiscountProduct
        {
            get
            {
                return this.DiscountProductField;
            }
            set
            {
                this.DiscountProductField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class Product : object
    {
        
        private int PGroupIdField;
        
        private long AmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PGroupId
        {
            get
            {
                return this.PGroupIdField;
            }
            set
            {
                this.PGroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientPaymentResponseDataBase", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pec.shaparak.ir.ClientSaleResponseData))]
    public partial class ClientPaymentResponseDataBase : object
    {
        
        private long TokenField;
        
        private string MessageField;
        
        private short StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public short Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientSaleResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class ClientSaleResponseData : pec.shaparak.ir.ClientPaymentResponseDataBase
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", ConfigurationName="pec.shaparak.ir.SaleServiceSoap")]
    public interface SaleServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService/SalePaymentRequest", ReplyAction="*")]
        pec.shaparak.ir.SalePaymentRequestResponse SalePaymentRequest(pec.shaparak.ir.SalePaymentRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService/SalePaymentRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<pec.shaparak.ir.SalePaymentRequestResponse> SalePaymentRequestAsync(pec.shaparak.ir.SalePaymentRequestRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService/SalePaymentWithId", ReplyAction="*")]
        pec.shaparak.ir.SalePaymentWithIdResponse SalePaymentWithId(pec.shaparak.ir.SalePaymentWithIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService/SalePaymentWithId", ReplyAction="*")]
        System.Threading.Tasks.Task<pec.shaparak.ir.SalePaymentWithIdResponse> SalePaymentWithIdAsync(pec.shaparak.ir.SalePaymentWithIdRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService/UDSalePaymentRequest", ReplyAction="*")]
        pec.shaparak.ir.UDSalePaymentRequestResponse UDSalePaymentRequest(pec.shaparak.ir.UDSalePaymentRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService/UDSalePaymentRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<pec.shaparak.ir.UDSalePaymentRequestResponse> UDSalePaymentRequestAsync(pec.shaparak.ir.UDSalePaymentRequestRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService/SalePaymentWithDiscount", ReplyAction="*")]
        pec.shaparak.ir.SalePaymentWithDiscountResponse SalePaymentWithDiscount(pec.shaparak.ir.SalePaymentWithDiscountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService/SalePaymentWithDiscount", ReplyAction="*")]
        System.Threading.Tasks.Task<pec.shaparak.ir.SalePaymentWithDiscountResponse> SalePaymentWithDiscountAsync(pec.shaparak.ir.SalePaymentWithDiscountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalePaymentRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalePaymentRequest", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", Order=0)]
        public pec.shaparak.ir.SalePaymentRequestRequestBody Body;
        
        public SalePaymentRequestRequest()
        {
        }
        
        public SalePaymentRequestRequest(pec.shaparak.ir.SalePaymentRequestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class SalePaymentRequestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public pec.shaparak.ir.ClientSaleRequestData requestData;
        
        public SalePaymentRequestRequestBody()
        {
        }
        
        public SalePaymentRequestRequestBody(pec.shaparak.ir.ClientSaleRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalePaymentRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalePaymentRequestResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", Order=0)]
        public pec.shaparak.ir.SalePaymentRequestResponseBody Body;
        
        public SalePaymentRequestResponse()
        {
        }
        
        public SalePaymentRequestResponse(pec.shaparak.ir.SalePaymentRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class SalePaymentRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public pec.shaparak.ir.ClientSaleResponseData SalePaymentRequestResult;
        
        public SalePaymentRequestResponseBody()
        {
        }
        
        public SalePaymentRequestResponseBody(pec.shaparak.ir.ClientSaleResponseData SalePaymentRequestResult)
        {
            this.SalePaymentRequestResult = SalePaymentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalePaymentWithIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalePaymentWithId", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", Order=0)]
        public pec.shaparak.ir.SalePaymentWithIdRequestBody Body;
        
        public SalePaymentWithIdRequest()
        {
        }
        
        public SalePaymentWithIdRequest(pec.shaparak.ir.SalePaymentWithIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class SalePaymentWithIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public pec.shaparak.ir.ClientSaleRequestData requestData;
        
        public SalePaymentWithIdRequestBody()
        {
        }
        
        public SalePaymentWithIdRequestBody(pec.shaparak.ir.ClientSaleRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalePaymentWithIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalePaymentWithIdResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", Order=0)]
        public pec.shaparak.ir.SalePaymentWithIdResponseBody Body;
        
        public SalePaymentWithIdResponse()
        {
        }
        
        public SalePaymentWithIdResponse(pec.shaparak.ir.SalePaymentWithIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class SalePaymentWithIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public pec.shaparak.ir.ClientSaleResponseData SalePaymentWithIdResult;
        
        public SalePaymentWithIdResponseBody()
        {
        }
        
        public SalePaymentWithIdResponseBody(pec.shaparak.ir.ClientSaleResponseData SalePaymentWithIdResult)
        {
            this.SalePaymentWithIdResult = SalePaymentWithIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UDSalePaymentRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UDSalePaymentRequest", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", Order=0)]
        public pec.shaparak.ir.UDSalePaymentRequestRequestBody Body;
        
        public UDSalePaymentRequestRequest()
        {
        }
        
        public UDSalePaymentRequestRequest(pec.shaparak.ir.UDSalePaymentRequestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class UDSalePaymentRequestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public pec.shaparak.ir.ClientSaleRequestData requestData;
        
        public UDSalePaymentRequestRequestBody()
        {
        }
        
        public UDSalePaymentRequestRequestBody(pec.shaparak.ir.ClientSaleRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UDSalePaymentRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UDSalePaymentRequestResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", Order=0)]
        public pec.shaparak.ir.UDSalePaymentRequestResponseBody Body;
        
        public UDSalePaymentRequestResponse()
        {
        }
        
        public UDSalePaymentRequestResponse(pec.shaparak.ir.UDSalePaymentRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class UDSalePaymentRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public pec.shaparak.ir.ClientPaymentResponseDataBase UDSalePaymentRequestResult;
        
        public UDSalePaymentRequestResponseBody()
        {
        }
        
        public UDSalePaymentRequestResponseBody(pec.shaparak.ir.ClientPaymentResponseDataBase UDSalePaymentRequestResult)
        {
            this.UDSalePaymentRequestResult = UDSalePaymentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalePaymentWithDiscountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalePaymentWithDiscount", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", Order=0)]
        public pec.shaparak.ir.SalePaymentWithDiscountRequestBody Body;
        
        public SalePaymentWithDiscountRequest()
        {
        }
        
        public SalePaymentWithDiscountRequest(pec.shaparak.ir.SalePaymentWithDiscountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class SalePaymentWithDiscountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public pec.shaparak.ir.ClientSaleDiscountRequestData requestData;
        
        public SalePaymentWithDiscountRequestBody()
        {
        }
        
        public SalePaymentWithDiscountRequestBody(pec.shaparak.ir.ClientSaleDiscountRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalePaymentWithDiscountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalePaymentWithDiscountResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", Order=0)]
        public pec.shaparak.ir.SalePaymentWithDiscountResponseBody Body;
        
        public SalePaymentWithDiscountResponse()
        {
        }
        
        public SalePaymentWithDiscountResponse(pec.shaparak.ir.SalePaymentWithDiscountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService")]
    public partial class SalePaymentWithDiscountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public pec.shaparak.ir.ClientSaleResponseData SalePaymentWithDiscountResult;
        
        public SalePaymentWithDiscountResponseBody()
        {
        }
        
        public SalePaymentWithDiscountResponseBody(pec.shaparak.ir.ClientSaleResponseData SalePaymentWithDiscountResult)
        {
            this.SalePaymentWithDiscountResult = SalePaymentWithDiscountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface SaleServiceSoapChannel : pec.shaparak.ir.SaleServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SaleServiceSoapClient : System.ServiceModel.ClientBase<pec.shaparak.ir.SaleServiceSoap>, pec.shaparak.ir.SaleServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SaleServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SaleServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SaleServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaleServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SaleServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaleServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SaleServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SaleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pec.shaparak.ir.SalePaymentRequestResponse pec.shaparak.ir.SaleServiceSoap.SalePaymentRequest(pec.shaparak.ir.SalePaymentRequestRequest request)
        {
            return base.Channel.SalePaymentRequest(request);
        }
        
        public pec.shaparak.ir.ClientSaleResponseData SalePaymentRequest(pec.shaparak.ir.ClientSaleRequestData requestData)
        {
            pec.shaparak.ir.SalePaymentRequestRequest inValue = new pec.shaparak.ir.SalePaymentRequestRequest();
            inValue.Body = new pec.shaparak.ir.SalePaymentRequestRequestBody();
            inValue.Body.requestData = requestData;
            pec.shaparak.ir.SalePaymentRequestResponse retVal = ((pec.shaparak.ir.SaleServiceSoap)(this)).SalePaymentRequest(inValue);
            return retVal.Body.SalePaymentRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pec.shaparak.ir.SalePaymentRequestResponse> pec.shaparak.ir.SaleServiceSoap.SalePaymentRequestAsync(pec.shaparak.ir.SalePaymentRequestRequest request)
        {
            return base.Channel.SalePaymentRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<pec.shaparak.ir.SalePaymentRequestResponse> SalePaymentRequestAsync(pec.shaparak.ir.ClientSaleRequestData requestData)
        {
            pec.shaparak.ir.SalePaymentRequestRequest inValue = new pec.shaparak.ir.SalePaymentRequestRequest();
            inValue.Body = new pec.shaparak.ir.SalePaymentRequestRequestBody();
            inValue.Body.requestData = requestData;
            return ((pec.shaparak.ir.SaleServiceSoap)(this)).SalePaymentRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pec.shaparak.ir.SalePaymentWithIdResponse pec.shaparak.ir.SaleServiceSoap.SalePaymentWithId(pec.shaparak.ir.SalePaymentWithIdRequest request)
        {
            return base.Channel.SalePaymentWithId(request);
        }
        
        public pec.shaparak.ir.ClientSaleResponseData SalePaymentWithId(pec.shaparak.ir.ClientSaleRequestData requestData)
        {
            pec.shaparak.ir.SalePaymentWithIdRequest inValue = new pec.shaparak.ir.SalePaymentWithIdRequest();
            inValue.Body = new pec.shaparak.ir.SalePaymentWithIdRequestBody();
            inValue.Body.requestData = requestData;
            pec.shaparak.ir.SalePaymentWithIdResponse retVal = ((pec.shaparak.ir.SaleServiceSoap)(this)).SalePaymentWithId(inValue);
            return retVal.Body.SalePaymentWithIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pec.shaparak.ir.SalePaymentWithIdResponse> pec.shaparak.ir.SaleServiceSoap.SalePaymentWithIdAsync(pec.shaparak.ir.SalePaymentWithIdRequest request)
        {
            return base.Channel.SalePaymentWithIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<pec.shaparak.ir.SalePaymentWithIdResponse> SalePaymentWithIdAsync(pec.shaparak.ir.ClientSaleRequestData requestData)
        {
            pec.shaparak.ir.SalePaymentWithIdRequest inValue = new pec.shaparak.ir.SalePaymentWithIdRequest();
            inValue.Body = new pec.shaparak.ir.SalePaymentWithIdRequestBody();
            inValue.Body.requestData = requestData;
            return ((pec.shaparak.ir.SaleServiceSoap)(this)).SalePaymentWithIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pec.shaparak.ir.UDSalePaymentRequestResponse pec.shaparak.ir.SaleServiceSoap.UDSalePaymentRequest(pec.shaparak.ir.UDSalePaymentRequestRequest request)
        {
            return base.Channel.UDSalePaymentRequest(request);
        }
        
        public pec.shaparak.ir.ClientPaymentResponseDataBase UDSalePaymentRequest(pec.shaparak.ir.ClientSaleRequestData requestData)
        {
            pec.shaparak.ir.UDSalePaymentRequestRequest inValue = new pec.shaparak.ir.UDSalePaymentRequestRequest();
            inValue.Body = new pec.shaparak.ir.UDSalePaymentRequestRequestBody();
            inValue.Body.requestData = requestData;
            pec.shaparak.ir.UDSalePaymentRequestResponse retVal = ((pec.shaparak.ir.SaleServiceSoap)(this)).UDSalePaymentRequest(inValue);
            return retVal.Body.UDSalePaymentRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pec.shaparak.ir.UDSalePaymentRequestResponse> pec.shaparak.ir.SaleServiceSoap.UDSalePaymentRequestAsync(pec.shaparak.ir.UDSalePaymentRequestRequest request)
        {
            return base.Channel.UDSalePaymentRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<pec.shaparak.ir.UDSalePaymentRequestResponse> UDSalePaymentRequestAsync(pec.shaparak.ir.ClientSaleRequestData requestData)
        {
            pec.shaparak.ir.UDSalePaymentRequestRequest inValue = new pec.shaparak.ir.UDSalePaymentRequestRequest();
            inValue.Body = new pec.shaparak.ir.UDSalePaymentRequestRequestBody();
            inValue.Body.requestData = requestData;
            return ((pec.shaparak.ir.SaleServiceSoap)(this)).UDSalePaymentRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pec.shaparak.ir.SalePaymentWithDiscountResponse pec.shaparak.ir.SaleServiceSoap.SalePaymentWithDiscount(pec.shaparak.ir.SalePaymentWithDiscountRequest request)
        {
            return base.Channel.SalePaymentWithDiscount(request);
        }
        
        public pec.shaparak.ir.ClientSaleResponseData SalePaymentWithDiscount(pec.shaparak.ir.ClientSaleDiscountRequestData requestData)
        {
            pec.shaparak.ir.SalePaymentWithDiscountRequest inValue = new pec.shaparak.ir.SalePaymentWithDiscountRequest();
            inValue.Body = new pec.shaparak.ir.SalePaymentWithDiscountRequestBody();
            inValue.Body.requestData = requestData;
            pec.shaparak.ir.SalePaymentWithDiscountResponse retVal = ((pec.shaparak.ir.SaleServiceSoap)(this)).SalePaymentWithDiscount(inValue);
            return retVal.Body.SalePaymentWithDiscountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<pec.shaparak.ir.SalePaymentWithDiscountResponse> pec.shaparak.ir.SaleServiceSoap.SalePaymentWithDiscountAsync(pec.shaparak.ir.SalePaymentWithDiscountRequest request)
        {
            return base.Channel.SalePaymentWithDiscountAsync(request);
        }
        
        public System.Threading.Tasks.Task<pec.shaparak.ir.SalePaymentWithDiscountResponse> SalePaymentWithDiscountAsync(pec.shaparak.ir.ClientSaleDiscountRequestData requestData)
        {
            pec.shaparak.ir.SalePaymentWithDiscountRequest inValue = new pec.shaparak.ir.SalePaymentWithDiscountRequest();
            inValue.Body = new pec.shaparak.ir.SalePaymentWithDiscountRequestBody();
            inValue.Body.requestData = requestData;
            return ((pec.shaparak.ir.SaleServiceSoap)(this)).SalePaymentWithDiscountAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SaleServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SaleServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SaleServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://pec.shaparak.ir/NewIPGServices/Sale/SaleService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SaleServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://pec.shaparak.ir/NewIPGServices/Sale/SaleService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SaleServiceSoap,
            
            SaleServiceSoap12,
        }
    }
}
