//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ipgsoap.asanpardakht.ir
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionDataPackage", Namespace="http://tempuri.org/")]
    public partial class TransactionDataPackage : object
    {
        
        private int FetchResultField;
        
        private System.DateTime ReportDateField;
        
        private ipgsoap.asanpardakht.ir.TransactionStatus[] TransactionListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FetchResult
        {
            get
            {
                return this.FetchResultField;
            }
            set
            {
                this.FetchResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ReportDate
        {
            get
            {
                return this.ReportDateField;
            }
            set
            {
                this.ReportDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ipgsoap.asanpardakht.ir.TransactionStatus[] TransactionList
        {
            get
            {
                return this.TransactionListField;
            }
            set
            {
                this.TransactionListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatus", Namespace="http://tempuri.org/")]
    public partial class TransactionStatus : object
    {
        
        private int EMerchantConfigIDField;
        
        private long LocalInvoiceIDField;
        
        private System.DateTime OperationRequestDateField;
        
        private System.DateTime MerchantLocalDateField;
        
        private long RequestedAmountInRialsField;
        
        private string AdditionalDataField;
        
        private int ServiceTypeIDField;
        
        private string CallbackURLField;
        
        private string PayerIDField;
        
        private string TokenField;
        
        private long PayGateTranIDField;
        
        private System.DateTime TransactionDateField;
        
        private string CardNumberField;
        
        private int StanField;
        
        private long ActualTrxAmountField;
        
        private string BillIDField;
        
        private string PaymentIDField;
        
        private string TrxResultCodeField;
        
        private bool MainTrxWasSuccessfulField;
        
        private string RRNField;
        
        private bool IsVerifiedField;
        
        private System.Nullable<System.DateTime> VerifyRequestDateField;
        
        private bool ReconcilationSucceededField;
        
        private System.Nullable<System.DateTime> ReconcilationRequestDateField;
        
        private bool IsReconcilationRequestedAutomaticallyField;
        
        private System.Nullable<System.DateTime> ReconcilationTryDateField;
        
        private bool ReversalSucceededField;
        
        private System.Nullable<System.DateTime> ReversalRequestDateField;
        
        private bool IsReversalRequestedAutomaticallyField;
        
        private System.Nullable<System.DateTime> ReversalTryDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EMerchantConfigID
        {
            get
            {
                return this.EMerchantConfigIDField;
            }
            set
            {
                this.EMerchantConfigIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long LocalInvoiceID
        {
            get
            {
                return this.LocalInvoiceIDField;
            }
            set
            {
                this.LocalInvoiceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime OperationRequestDate
        {
            get
            {
                return this.OperationRequestDateField;
            }
            set
            {
                this.OperationRequestDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime MerchantLocalDate
        {
            get
            {
                return this.MerchantLocalDateField;
            }
            set
            {
                this.MerchantLocalDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long RequestedAmountInRials
        {
            get
            {
                return this.RequestedAmountInRialsField;
            }
            set
            {
                this.RequestedAmountInRialsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int ServiceTypeID
        {
            get
            {
                return this.ServiceTypeIDField;
            }
            set
            {
                this.ServiceTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CallbackURL
        {
            get
            {
                return this.CallbackURLField;
            }
            set
            {
                this.CallbackURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PayerID
        {
            get
            {
                return this.PayerIDField;
            }
            set
            {
                this.PayerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public long PayGateTranID
        {
            get
            {
                return this.PayGateTranIDField;
            }
            set
            {
                this.PayGateTranIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime TransactionDate
        {
            get
            {
                return this.TransactionDateField;
            }
            set
            {
                this.TransactionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int Stan
        {
            get
            {
                return this.StanField;
            }
            set
            {
                this.StanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public long ActualTrxAmount
        {
            get
            {
                return this.ActualTrxAmountField;
            }
            set
            {
                this.ActualTrxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string BillID
        {
            get
            {
                return this.BillIDField;
            }
            set
            {
                this.BillIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string PaymentID
        {
            get
            {
                return this.PaymentIDField;
            }
            set
            {
                this.PaymentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string TrxResultCode
        {
            get
            {
                return this.TrxResultCodeField;
            }
            set
            {
                this.TrxResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool MainTrxWasSuccessful
        {
            get
            {
                return this.MainTrxWasSuccessfulField;
            }
            set
            {
                this.MainTrxWasSuccessfulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string RRN
        {
            get
            {
                return this.RRNField;
            }
            set
            {
                this.RRNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public bool IsVerified
        {
            get
            {
                return this.IsVerifiedField;
            }
            set
            {
                this.IsVerifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public System.Nullable<System.DateTime> VerifyRequestDate
        {
            get
            {
                return this.VerifyRequestDateField;
            }
            set
            {
                this.VerifyRequestDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public bool ReconcilationSucceeded
        {
            get
            {
                return this.ReconcilationSucceededField;
            }
            set
            {
                this.ReconcilationSucceededField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.Nullable<System.DateTime> ReconcilationRequestDate
        {
            get
            {
                return this.ReconcilationRequestDateField;
            }
            set
            {
                this.ReconcilationRequestDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public bool IsReconcilationRequestedAutomatically
        {
            get
            {
                return this.IsReconcilationRequestedAutomaticallyField;
            }
            set
            {
                this.IsReconcilationRequestedAutomaticallyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public System.Nullable<System.DateTime> ReconcilationTryDate
        {
            get
            {
                return this.ReconcilationTryDateField;
            }
            set
            {
                this.ReconcilationTryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public bool ReversalSucceeded
        {
            get
            {
                return this.ReversalSucceededField;
            }
            set
            {
                this.ReversalSucceededField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public System.Nullable<System.DateTime> ReversalRequestDate
        {
            get
            {
                return this.ReversalRequestDateField;
            }
            set
            {
                this.ReversalRequestDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public bool IsReversalRequestedAutomatically
        {
            get
            {
                return this.IsReversalRequestedAutomaticallyField;
            }
            set
            {
                this.IsReversalRequestedAutomaticallyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public System.Nullable<System.DateTime> ReversalTryDate
        {
            get
            {
                return this.ReversalTryDateField;
            }
            set
            {
                this.ReversalTryDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ipgsoap.asanpardakht.ir.merchantservicesSoap")]
    public interface merchantservicesSoap
    {
        
        // CODEGEN: Generating message contract since element name encryptedRequest from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestOperation", ReplyAction="*")]
        ipgsoap.asanpardakht.ir.RequestOperationResponse RequestOperation(ipgsoap.asanpardakht.ir.RequestOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestOperationResponse> RequestOperationAsync(ipgsoap.asanpardakht.ir.RequestOperationRequest request);
        
        // CODEGEN: Generating message contract since element name encryptedCredentials from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestReconciliation", ReplyAction="*")]
        ipgsoap.asanpardakht.ir.RequestReconciliationResponse RequestReconciliation(ipgsoap.asanpardakht.ir.RequestReconciliationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestReconciliation", ReplyAction="*")]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestReconciliationResponse> RequestReconciliationAsync(ipgsoap.asanpardakht.ir.RequestReconciliationRequest request);
        
        // CODEGEN: Generating message contract since element name encryptedCredentials from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestVerification", ReplyAction="*")]
        ipgsoap.asanpardakht.ir.RequestVerificationResponse RequestVerification(ipgsoap.asanpardakht.ir.RequestVerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestVerificationResponse> RequestVerificationAsync(ipgsoap.asanpardakht.ir.RequestVerificationRequest request);
        
        // CODEGEN: Generating message contract since element name encryptedCredentials from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancellVerification", ReplyAction="*")]
        ipgsoap.asanpardakht.ir.CancellVerificationResponse CancellVerification(ipgsoap.asanpardakht.ir.CancellVerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancellVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.CancellVerificationResponse> CancellVerificationAsync(ipgsoap.asanpardakht.ir.CancellVerificationRequest request);
        
        // CODEGEN: Generating message contract since element name encryptedCredentials from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestReversal", ReplyAction="*")]
        ipgsoap.asanpardakht.ir.RequestReversalResponse RequestReversal(ipgsoap.asanpardakht.ir.RequestReversalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestReversal", ReplyAction="*")]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestReversalResponse> RequestReversalAsync(ipgsoap.asanpardakht.ir.RequestReversalRequest request);
        
        // CODEGEN: Generating message contract since element name encryptedCredintials from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrxStatusFromLocalInvoiceID", ReplyAction="*")]
        ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDResponse TrxStatusFromLocalInvoiceID(ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrxStatusFromLocalInvoiceID", ReplyAction="*")]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDResponse> TrxStatusFromLocalInvoiceIDAsync(ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOperationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOperation", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.RequestOperationRequestBody Body;
        
        public RequestOperationRequest()
        {
        }
        
        public RequestOperationRequest(ipgsoap.asanpardakht.ir.RequestOperationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestOperationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedRequest;
        
        public RequestOperationRequestBody()
        {
        }
        
        public RequestOperationRequestBody(int merchantConfigurationID, string encryptedRequest)
        {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedRequest = encryptedRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestOperationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOperationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.RequestOperationResponseBody Body;
        
        public RequestOperationResponse()
        {
        }
        
        public RequestOperationResponse(ipgsoap.asanpardakht.ir.RequestOperationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestOperationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestOperationResult;
        
        public RequestOperationResponseBody()
        {
        }
        
        public RequestOperationResponseBody(string RequestOperationResult)
        {
            this.RequestOperationResult = RequestOperationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestReconciliationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestReconciliation", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.RequestReconciliationRequestBody Body;
        
        public RequestReconciliationRequest()
        {
        }
        
        public RequestReconciliationRequest(ipgsoap.asanpardakht.ir.RequestReconciliationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestReconciliationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedCredentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong payGateTranID;
        
        public RequestReconciliationRequestBody()
        {
        }
        
        public RequestReconciliationRequestBody(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedCredentials = encryptedCredentials;
            this.payGateTranID = payGateTranID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestReconciliationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestReconciliationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.RequestReconciliationResponseBody Body;
        
        public RequestReconciliationResponse()
        {
        }
        
        public RequestReconciliationResponse(ipgsoap.asanpardakht.ir.RequestReconciliationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestReconciliationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestReconciliationResult;
        
        public RequestReconciliationResponseBody()
        {
        }
        
        public RequestReconciliationResponseBody(string RequestReconciliationResult)
        {
            this.RequestReconciliationResult = RequestReconciliationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestVerificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestVerification", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.RequestVerificationRequestBody Body;
        
        public RequestVerificationRequest()
        {
        }
        
        public RequestVerificationRequest(ipgsoap.asanpardakht.ir.RequestVerificationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestVerificationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedCredentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong payGateTranID;
        
        public RequestVerificationRequestBody()
        {
        }
        
        public RequestVerificationRequestBody(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedCredentials = encryptedCredentials;
            this.payGateTranID = payGateTranID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestVerificationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestVerificationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.RequestVerificationResponseBody Body;
        
        public RequestVerificationResponse()
        {
        }
        
        public RequestVerificationResponse(ipgsoap.asanpardakht.ir.RequestVerificationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestVerificationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestVerificationResult;
        
        public RequestVerificationResponseBody()
        {
        }
        
        public RequestVerificationResponseBody(string RequestVerificationResult)
        {
            this.RequestVerificationResult = RequestVerificationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancellVerificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancellVerification", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.CancellVerificationRequestBody Body;
        
        public CancellVerificationRequest()
        {
        }
        
        public CancellVerificationRequest(ipgsoap.asanpardakht.ir.CancellVerificationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancellVerificationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedCredentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong payGateTranID;
        
        public CancellVerificationRequestBody()
        {
        }
        
        public CancellVerificationRequestBody(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedCredentials = encryptedCredentials;
            this.payGateTranID = payGateTranID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancellVerificationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancellVerificationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.CancellVerificationResponseBody Body;
        
        public CancellVerificationResponse()
        {
        }
        
        public CancellVerificationResponse(ipgsoap.asanpardakht.ir.CancellVerificationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancellVerificationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancellVerificationResult;
        
        public CancellVerificationResponseBody()
        {
        }
        
        public CancellVerificationResponseBody(string CancellVerificationResult)
        {
            this.CancellVerificationResult = CancellVerificationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestReversalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestReversal", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.RequestReversalRequestBody Body;
        
        public RequestReversalRequest()
        {
        }
        
        public RequestReversalRequest(ipgsoap.asanpardakht.ir.RequestReversalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestReversalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedCredentials;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong payGateTranID;
        
        public RequestReversalRequestBody()
        {
        }
        
        public RequestReversalRequestBody(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedCredentials = encryptedCredentials;
            this.payGateTranID = payGateTranID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestReversalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestReversalResponse", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.RequestReversalResponseBody Body;
        
        public RequestReversalResponse()
        {
        }
        
        public RequestReversalResponse(ipgsoap.asanpardakht.ir.RequestReversalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestReversalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestReversalResult;
        
        public RequestReversalResponseBody()
        {
        }
        
        public RequestReversalResponseBody(string RequestReversalResult)
        {
            this.RequestReversalResult = RequestReversalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrxStatusFromLocalInvoiceIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrxStatusFromLocalInvoiceID", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequestBody Body;
        
        public TrxStatusFromLocalInvoiceIDRequest()
        {
        }
        
        public TrxStatusFromLocalInvoiceIDRequest(ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrxStatusFromLocalInvoiceIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int merchantConfigurationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encryptedCredintials;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long localInvoiceID;
        
        public TrxStatusFromLocalInvoiceIDRequestBody()
        {
        }
        
        public TrxStatusFromLocalInvoiceIDRequestBody(int merchantConfigurationID, string encryptedCredintials, long localInvoiceID)
        {
            this.merchantConfigurationID = merchantConfigurationID;
            this.encryptedCredintials = encryptedCredintials;
            this.localInvoiceID = localInvoiceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrxStatusFromLocalInvoiceIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrxStatusFromLocalInvoiceIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDResponseBody Body;
        
        public TrxStatusFromLocalInvoiceIDResponse()
        {
        }
        
        public TrxStatusFromLocalInvoiceIDResponse(ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrxStatusFromLocalInvoiceIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ipgsoap.asanpardakht.ir.TransactionDataPackage TrxStatusFromLocalInvoiceIDResult;
        
        public TrxStatusFromLocalInvoiceIDResponseBody()
        {
        }
        
        public TrxStatusFromLocalInvoiceIDResponseBody(ipgsoap.asanpardakht.ir.TransactionDataPackage TrxStatusFromLocalInvoiceIDResult)
        {
            this.TrxStatusFromLocalInvoiceIDResult = TrxStatusFromLocalInvoiceIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface merchantservicesSoapChannel : ipgsoap.asanpardakht.ir.merchantservicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class merchantservicesSoapClient : System.ServiceModel.ClientBase<ipgsoap.asanpardakht.ir.merchantservicesSoap>, ipgsoap.asanpardakht.ir.merchantservicesSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public merchantservicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(merchantservicesSoapClient.GetBindingForEndpoint(endpointConfiguration), merchantservicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public merchantservicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(merchantservicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public merchantservicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(merchantservicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public merchantservicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ipgsoap.asanpardakht.ir.RequestOperationResponse ipgsoap.asanpardakht.ir.merchantservicesSoap.RequestOperation(ipgsoap.asanpardakht.ir.RequestOperationRequest request)
        {
            return base.Channel.RequestOperation(request);
        }
        
        public string RequestOperation(int merchantConfigurationID, string encryptedRequest)
        {
            ipgsoap.asanpardakht.ir.RequestOperationRequest inValue = new ipgsoap.asanpardakht.ir.RequestOperationRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.RequestOperationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedRequest = encryptedRequest;
            ipgsoap.asanpardakht.ir.RequestOperationResponse retVal = ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).RequestOperation(inValue);
            return retVal.Body.RequestOperationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestOperationResponse> ipgsoap.asanpardakht.ir.merchantservicesSoap.RequestOperationAsync(ipgsoap.asanpardakht.ir.RequestOperationRequest request)
        {
            return base.Channel.RequestOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestOperationResponse> RequestOperationAsync(int merchantConfigurationID, string encryptedRequest)
        {
            ipgsoap.asanpardakht.ir.RequestOperationRequest inValue = new ipgsoap.asanpardakht.ir.RequestOperationRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.RequestOperationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedRequest = encryptedRequest;
            return ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).RequestOperationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ipgsoap.asanpardakht.ir.RequestReconciliationResponse ipgsoap.asanpardakht.ir.merchantservicesSoap.RequestReconciliation(ipgsoap.asanpardakht.ir.RequestReconciliationRequest request)
        {
            return base.Channel.RequestReconciliation(request);
        }
        
        public string RequestReconciliation(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            ipgsoap.asanpardakht.ir.RequestReconciliationRequest inValue = new ipgsoap.asanpardakht.ir.RequestReconciliationRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.RequestReconciliationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            ipgsoap.asanpardakht.ir.RequestReconciliationResponse retVal = ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).RequestReconciliation(inValue);
            return retVal.Body.RequestReconciliationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestReconciliationResponse> ipgsoap.asanpardakht.ir.merchantservicesSoap.RequestReconciliationAsync(ipgsoap.asanpardakht.ir.RequestReconciliationRequest request)
        {
            return base.Channel.RequestReconciliationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestReconciliationResponse> RequestReconciliationAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            ipgsoap.asanpardakht.ir.RequestReconciliationRequest inValue = new ipgsoap.asanpardakht.ir.RequestReconciliationRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.RequestReconciliationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            return ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).RequestReconciliationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ipgsoap.asanpardakht.ir.RequestVerificationResponse ipgsoap.asanpardakht.ir.merchantservicesSoap.RequestVerification(ipgsoap.asanpardakht.ir.RequestVerificationRequest request)
        {
            return base.Channel.RequestVerification(request);
        }
        
        public string RequestVerification(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            ipgsoap.asanpardakht.ir.RequestVerificationRequest inValue = new ipgsoap.asanpardakht.ir.RequestVerificationRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.RequestVerificationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            ipgsoap.asanpardakht.ir.RequestVerificationResponse retVal = ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).RequestVerification(inValue);
            return retVal.Body.RequestVerificationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestVerificationResponse> ipgsoap.asanpardakht.ir.merchantservicesSoap.RequestVerificationAsync(ipgsoap.asanpardakht.ir.RequestVerificationRequest request)
        {
            return base.Channel.RequestVerificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestVerificationResponse> RequestVerificationAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            ipgsoap.asanpardakht.ir.RequestVerificationRequest inValue = new ipgsoap.asanpardakht.ir.RequestVerificationRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.RequestVerificationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            return ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).RequestVerificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ipgsoap.asanpardakht.ir.CancellVerificationResponse ipgsoap.asanpardakht.ir.merchantservicesSoap.CancellVerification(ipgsoap.asanpardakht.ir.CancellVerificationRequest request)
        {
            return base.Channel.CancellVerification(request);
        }
        
        public string CancellVerification(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            ipgsoap.asanpardakht.ir.CancellVerificationRequest inValue = new ipgsoap.asanpardakht.ir.CancellVerificationRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.CancellVerificationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            ipgsoap.asanpardakht.ir.CancellVerificationResponse retVal = ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).CancellVerification(inValue);
            return retVal.Body.CancellVerificationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.CancellVerificationResponse> ipgsoap.asanpardakht.ir.merchantservicesSoap.CancellVerificationAsync(ipgsoap.asanpardakht.ir.CancellVerificationRequest request)
        {
            return base.Channel.CancellVerificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.CancellVerificationResponse> CancellVerificationAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            ipgsoap.asanpardakht.ir.CancellVerificationRequest inValue = new ipgsoap.asanpardakht.ir.CancellVerificationRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.CancellVerificationRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            return ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).CancellVerificationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ipgsoap.asanpardakht.ir.RequestReversalResponse ipgsoap.asanpardakht.ir.merchantservicesSoap.RequestReversal(ipgsoap.asanpardakht.ir.RequestReversalRequest request)
        {
            return base.Channel.RequestReversal(request);
        }
        
        public string RequestReversal(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            ipgsoap.asanpardakht.ir.RequestReversalRequest inValue = new ipgsoap.asanpardakht.ir.RequestReversalRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.RequestReversalRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            ipgsoap.asanpardakht.ir.RequestReversalResponse retVal = ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).RequestReversal(inValue);
            return retVal.Body.RequestReversalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestReversalResponse> ipgsoap.asanpardakht.ir.merchantservicesSoap.RequestReversalAsync(ipgsoap.asanpardakht.ir.RequestReversalRequest request)
        {
            return base.Channel.RequestReversalAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.RequestReversalResponse> RequestReversalAsync(int merchantConfigurationID, string encryptedCredentials, ulong payGateTranID)
        {
            ipgsoap.asanpardakht.ir.RequestReversalRequest inValue = new ipgsoap.asanpardakht.ir.RequestReversalRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.RequestReversalRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredentials = encryptedCredentials;
            inValue.Body.payGateTranID = payGateTranID;
            return ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).RequestReversalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDResponse ipgsoap.asanpardakht.ir.merchantservicesSoap.TrxStatusFromLocalInvoiceID(ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequest request)
        {
            return base.Channel.TrxStatusFromLocalInvoiceID(request);
        }
        
        public ipgsoap.asanpardakht.ir.TransactionDataPackage TrxStatusFromLocalInvoiceID(int merchantConfigurationID, string encryptedCredintials, long localInvoiceID)
        {
            ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequest inValue = new ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredintials = encryptedCredintials;
            inValue.Body.localInvoiceID = localInvoiceID;
            ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDResponse retVal = ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).TrxStatusFromLocalInvoiceID(inValue);
            return retVal.Body.TrxStatusFromLocalInvoiceIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDResponse> ipgsoap.asanpardakht.ir.merchantservicesSoap.TrxStatusFromLocalInvoiceIDAsync(ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequest request)
        {
            return base.Channel.TrxStatusFromLocalInvoiceIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDResponse> TrxStatusFromLocalInvoiceIDAsync(int merchantConfigurationID, string encryptedCredintials, long localInvoiceID)
        {
            ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequest inValue = new ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequest();
            inValue.Body = new ipgsoap.asanpardakht.ir.TrxStatusFromLocalInvoiceIDRequestBody();
            inValue.Body.merchantConfigurationID = merchantConfigurationID;
            inValue.Body.encryptedCredintials = encryptedCredintials;
            inValue.Body.localInvoiceID = localInvoiceID;
            return ((ipgsoap.asanpardakht.ir.merchantservicesSoap)(this)).TrxStatusFromLocalInvoiceIDAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.merchantservicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.merchantservicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.merchantservicesSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ipgsoap.asanpardakht.ir/paygate/merchantservices.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.merchantservicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ipgsoap.asanpardakht.ir/paygate/merchantservices.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            merchantservicesSoap,
            
            merchantservicesSoap12,
        }
    }
}
